# configuration can be overridden via a DATABASE_URL environment variable
# http://edgeguides.rubyonrails.org/configuring.html#connection-preference
default: &default
  adapter: postgresql
  encoding: unicode

  # should match puma.rb
  # https://devcenter.heroku.com/articles/concurrency-and-database-connections#threaded-servers
  pool: <%= ENV["MAX_THREADS"] || 5 %>

development:
  <<: *default
  database: c2_development
test:
  <<: *default
# use 'url' rather than 'database' so that DATABASE_URL env var is not merged in.
# see URL at top of this file for docs.
  url: <% ENV['TEST_DATABASE_URL'] || 'postgresql://localhost/c2_test' %>
production: *default
